[[redirects]]
  from = "/*"
  to = "https://test.saasworksuite.com/:splat"
  headers = {Access-Control-Allow-Origin= "*", Access-Control-Allow-Credentials= "true", Access-Control-Allow-Methods= "GET, POST", Access-Control-Allow-Headers= "Content-Type, *"}
  status = 200
  force = true
