[build]
  command = “npm install && npm run build”
  functions = “functions/”

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/servers/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin= "*"}
  query = {path = “:path”}
